In [1]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
n_inputs = 3
n_neurons = 5

In [3]:
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

In [4]:
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

In [5]:
Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

In [6]:
init = tf.global_variables_initializer()

In [7]:
import numpy as np

In [8]:
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]])
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

In [9]:
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [10]:
print(Y0_val)

[[-0.8835299   0.9025558  -0.23154029 -0.96355164  0.4324425 ]
 [ 0.7393435   0.9999924  -0.8665323  -0.6246172   0.8852194 ]
 [ 0.9972265   1.         -0.9837447   0.48402378  0.9814619 ]
 [ 1.          1.          0.05322769  1.          0.98808223]]


In [11]:
print(Y1_val)

[[ 0.99999857  1.         -0.999929    0.9999991   0.995566  ]
 [-0.63687146  0.8477458   0.5047866   0.9934036  -0.9660777 ]
 [ 0.9999974   1.         -0.42805865  0.9999999  -0.9138781 ]
 [ 0.9999782   0.99991465  0.0494046   0.9999966  -0.98707485]]


In [12]:
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs_seqs, seqs = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1], dtype=tf.float32)

In [13]:
Y0, Y1 = outputs_seqs

In [14]:
tf.reset_default_graph()

n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

In [15]:
X_batch = np.array([
    [[0, 1, 2], [9, 9, 7]],
    [[3, 4, 5], [0, 0, 0]],
    [[9, 0, 1], [3, 2, 1]]
])

In [16]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [17]:
outputs_val

array([[[-0.8667826 , -0.46119165,  0.96141326,  0.39979112,
          0.79039353],
        [-0.925666  , -0.9999999 ,  0.99999994, -0.9016452 ,
          0.9778266 ]],

       [[-0.974887  , -0.9981169 ,  0.9999685 , -0.1335967 ,
          0.95994264],
        [-0.5293158 ,  0.31099764, -0.45216054,  0.75524426,
          0.47355476]],

       [[ 0.996893  , -0.99995565, -0.26084298, -0.9993805 ,
         -0.9924056 ],
        [-0.07413124, -0.9984098 ,  0.95881504, -0.82686985,
          0.3785333 ]]], dtype=float32)

In [18]:
tf.reset_default_graph()

seq_length = tf.placeholder(tf.int32, [None])
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)


In [19]:
X_batch = np.array([
    [[0, 1, 2], [9, 8, 7]],
    [[3, 4, 5], [0, 0, 0]],
    [[6, 7, 8], [6, 5, 4]],
    [[9, 0, 1], [3, 2, 1]]
])

In [20]:
seq_length_batch = np.array([2, 1, 2, 2])

In [21]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: seq_length_batch})

In [22]:
outputs_val

array([[[ 0.12329921, -0.04744981, -0.9393673 ,  0.06182215,
          0.49267176],
        [-0.9549257 , -0.1282666 , -1.        ,  0.9815445 ,
          1.        ]],

       [[-0.42666152, -0.04533911, -0.9999907 ,  0.55586493,
          0.99915993],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ]],

       [[-0.77612305, -0.04322813, -1.        ,  0.831123  ,
          0.999999  ],
        [-0.9330059 ,  0.40943727, -0.9999997 ,  0.84121805,
          0.99998844]],

       [[ 0.8062531 ,  0.99327403, -0.99827164,  0.9957853 ,
          0.99989337],
        [-0.25969303,  0.559296  , -0.999334  ,  0.85742706,
          0.9895261 ]]], dtype=float32)

In [23]:
states_val

array([[-0.9549257 , -0.1282666 , -1.        ,  0.9815445 ,  1.        ],
       [-0.42666152, -0.04533911, -0.9999907 ,  0.55586493,  0.99915993],
       [-0.9330059 ,  0.40943727, -0.9999997 ,  0.84121805,  0.99998844],
       [-0.25969303,  0.559296  , -0.999334  ,  0.85742706,  0.9895261 ]],
      dtype=float32)

In [24]:
tf.reset_default_graph()
n_steps = 28
n_inputs = 28
n_neurons = 150
n_outputs =10

learning_rate = 0.001

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32,[None])

with tf.variable_scope('rnn', initializer=tf.variance_scaling_initializer()):
    basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
    outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

logits = tf.layers.dense(states, n_outputs)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)

loss = tf.reduce_mean(xentropy)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)
correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()

In [25]:
from tensorflow.examples.tutorials.mnist import input_data

In [26]:
mnist = input_data.read_data_sets('/tmp/data/')
X_test = mnist.test.images.reshape((-1, n_steps, n_inputs))
y_test = mnist.test.labels

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [27]:
n_epochs = 100
batch_size = 150

In [28]:
with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch = mnist.train.next_batch(batch_size)
            X_batch = X_batch.reshape(-1, n_steps, n_inputs)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        acc_train = accuracy.eval(feed_dict={X:X_batch, y:y_batch})
        acc_test = accuracy.eval(feed_dict={X: X_test, y: y_test})
        print(epoch, " Train accuracy: ",acc_train, "Test accuracy: ",acc_test)

0  Train accuracy:  0.8933333 Test accuracy:  0.9207
1  Train accuracy:  0.96666664 Test accuracy:  0.9445
2  Train accuracy:  0.98 Test accuracy:  0.9531
3  Train accuracy:  0.9533333 Test accuracy:  0.9589
4  Train accuracy:  0.97333336 Test accuracy:  0.9541
5  Train accuracy:  0.98 Test accuracy:  0.9649
6  Train accuracy:  0.98 Test accuracy:  0.9649
7  Train accuracy:  0.96 Test accuracy:  0.9674
8  Train accuracy:  0.98 Test accuracy:  0.9665
9  Train accuracy:  0.9866667 Test accuracy:  0.9678
10  Train accuracy:  0.99333334 Test accuracy:  0.9687
11  Train accuracy:  0.98 Test accuracy:  0.9731
12  Train accuracy:  0.99333334 Test accuracy:  0.9698
13  Train accuracy:  1.0 Test accuracy:  0.9734
14  Train accuracy:  0.94666666 Test accuracy:  0.9777
15  Train accuracy:  0.99333334 Test accuracy:  0.977
16  Train accuracy:  0.98 Test accuracy:  0.977
17  Train accuracy:  0.98 Test accuracy:  0.9706
18  Train accuracy:  0.9866667 Test accuracy:  0.9741
19  Train accuracy:  0.986

In [29]:
tf.reset_default_graph()
n_steps = 20
n_inputs = 1
n_neurons = 100
n_outputs = 1

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
cell = tf.contrib.rnn.OutputProjectionWrapper(tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu), output_size=n_outputs)
outputs, steps = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

learning_rate = 0.001

loss = tf.reduce_mean(tf.square(outputs - y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()

n_iterations = 2500
batch_size = 50

with tf.Session() as sess:
    init.run()
    for iteration in range(n_iterations):
        X_batch, y_batch = next_batch(batch_size, n_steps)
        sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        if iteration % 100 == 0:
            mse = loss.eval(feed_dict={X: X_batch, y:y_batch})
            print(iteration, ' mse: ', mse)


NameError: name 'next_batch' is not defined

In [ ]:
t_min, t_max = 0, 30

resolution = 0.1

def time_series(t):
    return t * np.sin(t) /  3 + 2 * np.sin(t * 5)

def next_batch(batch_size, n_steps):
    t0 = np.random.rand(batch_size, 1) * (t_max - t_min - n_steps * resolution)
    Ts = t0 + np.arange(0., n_steps + 1) * resolution
    ys = time_series(Ts)
    return ys[:, :-1].reshape(-1, n_steps, 1), ys[:, 1:].reshape(-1, n_steps, 1)

In [ ]:
t0 = np.random.rand(50, 1) * (t_max - t_min - n_steps * resolution)
Ts = t0 + np.arange(0., 20 + 1) * resolution
ys = time_series(Ts)

In [ ]:
ys[0]

In [ ]:
ys[0, :-1]

In [ ]:
ys[0, 1:]