In [1]:
from sklearn.datasets import fetch_mldata
import numpy as np

In [2]:
mnist = fetch_mldata('MNIST original')

In [3]:
X, y = mnist['data'], mnist['target']

In [4]:
train_index = np.arange(0,40000)
val_index = np.arange(40000, 50000)
test_index = np.arange(50000,70000)

In [5]:
X_train, y_train = X[train_index], y[train_index]
X_val, y_val = X[val_index], y[val_index]
X_test, y_test = X[test_index], y[test_index]

shuffle_index = np.random.permutation(40000)
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]

In [6]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [7]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, X_val, y_val, scoring='accuracy')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\ProgramData\Anaconda3\lib\sit

array([ 0.98590282,  0.97359736,  0.98289829])

In [8]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier()

forest_clf.fit(X_train, y_train)

cross_val_score(forest_clf, X_val, y_val, scoring='accuracy', cv=3)

array([ 0.98470306,  0.97929793,  0.98169817])

In [9]:
from sklearn.ensemble import ExtraTreesClassifier

extra_clf = ExtraTreesClassifier()

extra_clf.fit(X_train, y_train)

cross_val_score(extra_clf, X_val, y_val, scoring='accuracy', cv=3)

array([ 0.9880024 ,  0.98319832,  0.98469847])

In [10]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()

knn_clf.fit(X_train, y_train)

cross_val_score(knn_clf, X_val, y_val, scoring='accuracy', cv=3)

array([ 0.99490102,  0.99039904,  0.99159916])

In [14]:
from sklearn.ensemble import VotingClassifier

voting_clf = VotingClassifier(
    estimators=[('forest',RandomForestClassifier()), ('trees', ExtraTreesClassifier()), ('knn',KNeighborsClassifier())], 
    voting='hard'
)

voting_clf.fit(X_train, y_train)

cross_val_score(voting_clf, X_val, y_val, scoring='accuracy', cv=3)

array([ 0.99280144,  0.98979898,  0.98619862])

In [16]:
voting_soft_clf = VotingClassifier(
    estimators=[('forest',RandomForestClassifier()), ('trees', ExtraTreesClassifier()), ('knn',KNeighborsClassifier())], 
    voting='soft'
)

cross_val_score(voting_soft_clf, X_val, y_val, scoring='accuracy', cv=3)

array([ 0.99340132,  0.99189919,  0.99309931])

In [17]:
forest_predict = forest_clf.predict(X_train)
extra_predict = extra_clf.predict(X_train)
knn_pred = knn_clf.predict(X_train)